lib1090+
SeRoSystems/lib1090 pull request #1
Opened 2022-07-25 13:18 UTC by ibenacha

2022-07-27 17:11 UTC, affitz commented on src/main/java/de/serosystems/lib1090/msgs/modes/ACASActiveResolutionAdvisorReport.java
> +public class ACASActiveResolutionAdvisorReport extends ModeSDownlinkMsg implements Serializable {
There is a "y" missing in the class name.

2022-07-27 17:19 UTC, affitz requested changes
The overall structuring of the decoder within the libraries should be changed:

These decoders should not inherit from ModeSDownlinkMsg. BDS registers are not downlink messages, they are parts of two downlink messages, namely the two CommB downlink replies. The BDS decoders should only deal with decoding the [BDS data](https://github.com/SeRoSystems/lib1090/blob/master/src/main/java/de/serosystems/lib1090/msgs/modes/CommBAltitudeReply.java#L211). It should not be mixed with decoding the rest of the downlink replies which is already done in the existing CommB reply classes.

As a result of your design, you have a lot of redundant code that is identical in each of your classes below and is in addition redundant to what is already being done in the CommB reply decoders.

This needs to be restructured and the redundancy needs to be removed. I recommend to create a new interface or class called de.serosystems.lib1090.bds.BDSRegister and then each BDS decoder inherits from that.

2022-08-04 16:01 UTC, affitz requested changes
Thanks, looks much better now. Could you also add the respective Java doc? See the other lib1090 message classes. Best way to do it is to copy the descriptions of the fields from the Mode S spec. Cheers!

2022-08-10 06:55 UTC, ibenacha commented
I added some doc based on the document in my hands (ED-73E Mode S MOPS Vol 2). I will sync with Jorg regarding some reserved fields. for the time being, let me know if the existing doc match your expectation. Thanks.

2022-08-10 08:22 UTC, affitz approved these changes
Looks good, thanks!

2022-08-10 08:53 UTC, merged